export const LOGIN_POP_UP_NAME = process.env.LOGIN_POP_UP_NAME
export const ACCESS_TOKEN_STORAGE_KEY = process.env.ACCESS_TOKEN_STORAGE_KEY
export const ACCESS_TOKEN_HASH_KEY = process.env.ACCESS_TOKEN_HASH_KEY
