export const LOGIN_POP_UP_NAME = process.env.REACT_APP_LOGIN_POP_UP_NAME
export const ACCESS_TOKEN_STORAGE_KEY = process.env.REACT_APP_ACCESS_TOKEN_STORAGE_KEY
export const ACCESS_TOKEN_HASH_KEY = process.env.REACT_APP_ACCESS_TOKEN_HASH_KEY
export const SPOTIFY_CLIENT_ID = process.env.REACT_APP_SPOTIFY_CLIENT_ID
